# -*- coding: utf-8 -*-
"""Question1_Pandas_DataFrame.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13zuFIhuQ8jhGqNWG8wIzANzWR1RYqCZM
"""

# Step 1: Create DataFrame
data = {
    "StudentID": [101,102,103,104,105,106,107,108,109,110],
    "Name": ["Alice","Bob","Charlie","Diana","Ethan","Fiona","George","Hannah","Ivan","Julia"],
    "Age": [20,21,19,22,20,21,23,19,22,20],
    "Marks": [88,75,92,65,78,85,70,95,60,80],
    "Grade": ["A","B","A","C","B","A","B","A","C","B"]
}

import pandas as pd
df = pd.DataFrame(data)

# Step 2: Save DataFrame as CSV
df.to_csv("students.csv", index=False)

# Step 3: Reload CSV into new DataFrame
df2 = pd.read_csv("students.csv")

# Step 4: Display first 3 rows
print("First 3 rows:")
print(df2.head(3))

# Step 5: Statistical summary
print("\nStatistical Summary:")
print(df2.describe())

# Step 6: Explore data
print("\nShape of DataFrame:")
print(df2.shape)

print("\nData Types:")
print(df2.dtypes)

print("\nInfo:")
print(df2.info())